### ISSUE TITLE
Create Vercel Release on PR

### ISSUE THREAD

**Issue by mdroidian** [DiscourseGraph/discourse-graph#17]
Store in blob storage so that users can load the "dev" version via url before the versions are approved in Roam Depot.

See https://github.com/DiscourseGraphs/discourse-graph/blob/1da6d40965ddd4d0ab72f478466e2aecd992f88a/apps/roam/scripts/deploy.ts#L6

**Comment by mdroidian** [comment]
handle 
- `next build`
- deploy app to vercel on main/PR
- PR app to roam on main

example

```yaml
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
```
